# Generated by Django 3.2 on 2021-11-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='a',
            field=models.CharField(max_length=80, verbose_name='A选项'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='b',
            field=models.CharField(max_length=80, verbose_name='B选项'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='c',
            field=models.CharField(max_length=80, verbose_name='C选项'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='d',
            field=models.CharField(max_length=80, verbose_name='D选项'),
        ),
    ]
