# Generated by Django 3.2 on 2021-11-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20211116_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='title',
            field=models.TextField(max_length=500, verbose_name='题目'),
        ),
    ]
