# Generated by Django 3.2 on 2023-05-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_questionbank_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sclass',
            field=models.CharField(help_text='例如: 21-03', max_length=20, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='examtime',
            field=models.DateTimeField(verbose_name='考试开始时间'),
        ),
        migrations.CreateModel(
            name='ExamPaperQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.testpaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.questionbank')),
            ],
            options={
                'db_table': 'exam_paper_question',
            },
        ),
    ]
