# Generated by Django 3.2 on 2023-05-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_testpaper_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='pid',
            field=models.ManyToManyField(to='exam.QuestionBank'),
        ),
        migrations.DeleteModel(
            name='ExamPaperQuestion',
        ),
    ]
