# Generated by Django 3.2 on 2023-06-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20230521_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academy',
            old_name='id',
            new_name='Academyid',
        ),
        migrations.RenameField(
            model_name='academy',
            old_name='name',
            new_name='Academyname',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='id',
            new_name='Courseid',
        ),
        migrations.RenameField(
            model_name='major',
            old_name='id',
            new_name='Majorid',
        ),
        migrations.RenameField(
            model_name='questionbank',
            old_name='id',
            new_name='QuestionBankid',
        ),
        migrations.RenameField(
            model_name='testpaper',
            old_name='id',
            new_name='TestPaperid',
        ),
    ]
