# Generated by Django 3.2 on 2023-06-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20230602_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academy',
            old_name='Academyid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='academy',
            old_name='Academyname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Courseid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='major',
            old_name='Majorid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='questionbank',
            old_name='QuestionBankid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='testpaper',
            old_name='TestPaperid',
            new_name='id',
        ),
    ]
