# Generated by Django 3.2 on 2023-06-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20230602_1545'),
    ]

    operations = [
    ]
