# Generated by Django 3.2 on 2023-06-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20230606_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestquestionBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('QuestionBankid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.questionbank', verbose_name='题目序号')),
                ('Testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.testpaper', verbose_name='试卷序号')),
            ],
            options={
                'verbose_name': '试卷和题库',
                'verbose_name_plural': '试卷和题库',
            },
        ),
    ]
