# Generated by Django 3.2 on 2023-06-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_testquestionbank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpaper',
            name='pid',
        ),
    ]
